import{R as r,q as f,o as M,a1 as v,j as t,a2 as b,a3 as j}from"./DIBLJojdTQB51I2zM4gm.js";import{u as y}from"./BV-6LX_Gn8Wz_usUCJsP.js";import{u as C}from"./DMCex30FeWvvThtDj-pY.js";import{P as E}from"./BsHAe7mWCTqodyXnQ_D1.js";import{H as S}from"./CHC-6lQNrhE48vMQfRqn.js";import{M as A}from"./CRTgG9y7LkU-0dBMMAXs.js";const G=r.createContext(0),R=82,w=f.div`
	flex: 1 1 auto;
	overflow-y: auto;
	display: flex;
	flex-direction: column-reverse;
`,L=f.div`
	margin: 16px 16px 0 16px;
`;function P({guild:n,channel:e}){const l=y(),a=C("MessageList.tsx"),[d,c]=r.useState(!0),[D,m]=r.useState(!1),o=e.messages.groups,u=r.useRef(null),{width:p}=v({ref:u});r.useEffect(()=>{const i=E.getPermission(l.account.id,n,e).has("READ_MESSAGE_HISTORY");return m(i),n&&e&&e.messages.count===0&&e.getMessages(l,!0).then(g=>{g<50&&c(!1)}),()=>{a.debug("MessageList unmounted"),c(!0),m(!1)}},[n,e]);const x=r.useCallback(()=>{if(!e.messages.count){a.warn("channel has no messages, aborting!");return}const s=o[o.length-1];if(!s){a.warn("No last group found, aborting fetchMore");return}if("status"in s.messages[0])return;const i=s.messages[0].id;a.debug(`Fetching 50 messages before ${i} for channel ${e.id}`),e.getMessages(l,!1,50,i).then(g=>{g<50&&c(!1)})},[e,o]),h=r.useCallback(s=>t.jsx(A,{group:s},`messageGroup-${s.messages[s.messages.length-1].id}`),[o]);return t.jsx(G.Provider,{value:(p??0)-R,children:t.jsx(w,{id:"scrollable-div",ref:u,children:t.jsx(b,{dataLength:o.length,next:x,style:{display:"flex",flexDirection:"column-reverse",marginBottom:30,overflow:"hidden"},hasMore:d,inverse:!0,loader:t.jsx(j,{style:{display:"flex",justifyContent:"center",alignContent:"center",margin:30},color:"var(--primary)"}),scrollThreshold:.5,scrollableTarget:"scrollable-div",endMessage:t.jsxs(L,{children:[t.jsxs("h1",{style:{fontWeight:700,margin:"8px 0"},children:["Welcome to #",e.name,"!"]}),t.jsxs("p",{style:{color:"var(--text-secondary)"},children:["This is the start of the #",e.name," channel."]}),t.jsx(S,{})]}),children:o.map(s=>h(s))})})})}const k=M(P);export{k as M,G as a};
//# sourceMappingURL=CczqZ7h8UAHznLzR3Z96.js.map
